# Network Configuration
network.host=localhost
network.port=5432
network.timeout.ms=3000
#// max time to wait for tcp connection or failure

# Probe Configuration probe = check / test
probe.interval.ms=2000
probe.duration.minutes=1

# Anomaly Thresholds
latency.threshold.ms=100
db.connect.threshold.ms=200
db.query.threshold.ms=100

# PostgreSQL Configuration
db.url=jdbc:postgresql://localhost:5432/posdb
db.username=aayush.0_o
db.password=

# Log Directory
log.directory=logs